version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
  keycloak:
    image: hillamicro/noportal/keycloak
    build: keycloak
    stop_signal: SIGINT
    ports:
      - "8081:8080"
  eureka:
    image: hillamicro/noportal/eureka
    build: ../eureka-app
    stop_signal: SIGINT
    ports:
      - "8761:8761"
  gateway:
    image: hillamicro/noportal/gateway
    build: portal-gateway
    stop_signal: SIGINT
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761/eureka/
    depends_on:
      eureka:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    ports:
      - "8080:8080"
  microfrontend-a:
    image: hillamicro/noportal/microfrontend-a
    build: microfrontend-a
    stop_signal: SIGINT
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      eureka:
        condition: service_healthy
      rabbitmq:
        condition: service_started
  microfrontend-b:
    image: hillamicro/noportal/microfrontend-b
    build: microfrontend-b
    stop_signal: SIGINT
    environment:
      - EUREKA_SERVICE_URL=http://eureka:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      eureka:
        condition: service_healthy
      rabbitmq:
        condition: service_started
