spring:
    application:
        name: gateway-app
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVICE_URL}
