spring:
  application:
    name: hello-app
  devtools:
    restart:
      additional-exclude: dev/hilla/openapi.json
server:
  port: ${PORT:8083}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
  instance:
    metadata-map:
      microfrontend.title: Hello World
      microfrontend.importPath: /_apps/hello-app/VAADIN/build/hello-app-container.js
      microfrontend.moduleName: ./hello-app
      microfrontend.path: /hello
      microfrontend.tag: hello-app
      microfrontend.icon: "vaadin:car"
      microfrontend.requiresAuthentication: false

vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla
