spring:
  application:
    name: people-app
  devtools:
    restart:
      additional-exclude: dev/hilla/openapi.json
server:
  port: ${PORT:8084}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
  instance:
    metadata-map:
      microfrontend.title: People
      microfrontend.importPath: /_apps/people-app/VAADIN/build/people-app-container.js
      microfrontend.moduleName: ./people-app
      microfrontend.path: /people
      microfrontend.tag: people-app
      microfrontend.icon: "vaadin:users"
      microfrontend.requiresAuthentication: false

vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla
