version: "3.9"
services:
  eureka-app:
    image: microfrontend-hilla/eureka-app
    build: eureka-app
    stop_signal: SIGINT
  gateway-app:
    image: microfrontend-hilla/gateway-app
    build: gateway-app
    stop_signal: SIGINT
    environment:
      - EUREKA_SERVICE_URL=http://eureka-app:8761/eureka/
    depends_on:
      eureka-app:
        condition: service_healthy
    ports:
      - "8080:8080"
  portal-app:
    image: microfrontend-hilla/portal-app
    build: portal-app
    stop_signal: SIGINT
    environment:
      - EUREKA_SERVICE_URL=http://eureka-app:8761/eureka/
    depends_on:
      eureka-app:
        condition: service_healthy
