spring:
    application:
        name: portal-app
    devtools:
        restart:
            additional-exclude: dev/hilla/openapi.json
server:
    port: ${PORT:8082}
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
vaadin:
    whitelisted-packages: com.vaadin,org.vaadin,dev.hilla
