spring:
  application:
    name: frontend-a
  devtools:
    restart:
      additional-exclude: dev/hilla/openapi.json
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI:http://host.docker.internal:8081/realms/hillamicro}
server:
  port: ${PORT:8083}
  servlet:
    context-path: /frontend-a/
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://host.docker.internal:8761/eureka/}
  instance:
    metadata-map:
      frontend.title: Frontend A
    home-page-url: ${HOME_PAGE_URL:http://host.docker.internal:8080/frontend-a/}
vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla
